# Generated by Django 6.1 on 2026-08-08 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        ('users', '0002_user_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='email',
        ),
        migrations.AddField(
            model_name='checkout',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='users.user'),
        ),
    ]
